# Generated by Django 3.0 on 2021-04-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default=True, upload_to='upload/'),
        ),
    ]
